
 server:
  port: 9090
  

---
master: 
  user: 
    email: raghavendrakanekal5@gmail.com
    name: Admin
    
  

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/hms_project8
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true



  mail:  
    host: smtp.gmail.com
    port: 587
    username: kraghava112@gmail.com
    password: WelCome32!
    properties:
     mail:
      smtp:
       starttls:
         enable: true
    #access token : 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